modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Crimix/PermissionLevels/issues"

[[mods]]
modId="permissionlevels"
version="${file.jarVersion}"
displayName="Permission Levels"
updateJSONURL="https://raw.githubusercontent.com/Crimix/PermissionLevels/1.15/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/permission-levels"
logoFile="permissionlevels-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Control the ops'''

[[dependencies.permissionlevels]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.permissionlevels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
